# Computational coursework {#coursework .unnumbered}

::: {.mysummary}
There is one piece of computational coursework for MATH5835M Statistical Computing. This coursework is worth 20% of the module mark.

The coursework sheet is available in **[here in HTML format](https://mpaldridge.github.io/math5835/coursework/math5835-coursework.html)** or **<a href="https://mpaldridge.github.io/math5835/coursework/math5835-coursework.Rmd">here in R Markdown format</a>**.

The deadline for the coursework will be the penultimate day of the Autumn term, **Thursday 12 December ** at **1400**. (There is an optional deadline if you wish to get feedback on a draft of your work: Friday 6 December at 1400.)

Feedback on the final report and marks will be returned on Monday 13 January, the first day of the Spring term.
:::

## About the coursework

There is one piece of computational coursework for MATH5835M Statistical Computing. This coursework is worth 20% of the module mark.

This page contains all the administrative and organisational information about the coursework. A coursework sheet contains the tasks you must carry out. The coursework sheet is available in **[here in HTML format](https://mpaldridge.github.io/math5835/coursework/math5835-coursework.html)** or **<a href="https://mpaldridge.github.io/math5835/coursework/math5835-coursework.Rmd">here in R Markdown format</a>**. The HTML page can be opened in a standard web browser. The R Markdown version (which I personally prefer) should be downloaded then opened in RStudio; I recommend using the "Visual" editor -- see the button in the top left of the editing window.

The are two deadlines for this work. 

1. There is the **main submission deadline** which is the penultimate day of term, **Thursday 12 December** at **1400**. You must submit your work. Work that is submitted after this deadline will receive a penalty of 5% for every day or part-day late. Work that is more than 14 days late will not be marked and will receive 0. Work will be submitted electronically through Gradescope via the Minerva page for the module.

2. *Optionally*, you *may* also wish to get some brief informal feedback on your draft work before the main deadline. *If* you wish to get feedback on your draft work, you should submit that draft by Friday 6 December at 1400. I will return a small amount of general feedback about your work by Monday 9 December. I will not mark your draft, and the feedback will be a brief sentence or too that may be of a little help when completing the final version of your work. The quality of your draft submission will have no effect (either positive or negative) on the mark for your main submission, and there is no penalty if you choose not to take advantage of this offer. No extensions can be offered on the deadline for this informal feedback.

The Gradescope submission for the final report will open after 1400 on Friday 6 December (to avoid drafts for optional feedback getting mixed up with final reports). The Gradescope submission for optional feedback on draft work will be open from the computer practical sessions in week 9.

Your task is to write a short report in response to the tasks on the coursework sheet. Your report should include all the important R code you use and any important plots you draw. I call this a "report" because your work should be explained in detail, in full English-language sentences, with your solutions discussed and justified. Any code or figures included should be an integral part of your text, not just copy-pasted in at random, and should be fully explained within the text. However, other parts of a more formal report such as an introduction, literature review, conclusion, references, etc, are not required here.

There is *no page limit* for the report, although I expect that good reports will typically be around 5--7 pages. If your report is 4 pages or less, make sure you have completed all the tasks and fully explained your work. If your report has 8 pages or more, make sure you are not wandering from the point or including too many necessary figures.

Your report should be prepared electronically, but can be submitted in any sensible format -- I recommend PDF (whether produced by LaTeX, R Markdown, Microsoft Word, or any other way), but HTML or Word document are fine too.

There will be a computer practical in Week 9 where I will introduce the practical coursework in more detail. This is a good place to ask any questions you have about the coursework.

Places where you can get help with the coursework include:

* In the computer practical session.

* In my office hours -- Mondays 1500--1600 in my office, 9.10n in the "Maths Research Deck" area on the 9th floor of the EC Stoner building at staircase 1.

* By submitting your draft work for optional feedback, as discussed above.

Your report must be entirely your own work. You must not work together with others, and you must not use generative AI -- the coursework is **<span style="color:red;">RED</red> for use of AI** on the University's traffic light system, meaning the use of generative AI is forbidden. You must comply with [the University's rules on academic integrity](https://students.leeds.ac.uk/info/10110/academic-integrity).

If you encounter extraordinary unforeseeable personal circumstances that make it impossible for you to submit your coursework on time, you can apply for an deadline extension through [the usual mitigating circumstances procedure](https://students.leeds.ac.uk/info/10111/assessment/860/mitigating_circumstances). (Do not contact me about this -- I cannot unilaterally offer deadline extensions.)

## R and RStudio on University computers

A quick reminder on how to access R and RStudio on University computers.

1. **Open the AppsAnywhere portal** This should be a link on the desktop. If invited to run any software, accept.

2. **Load the language R** Search on AppsAnywhere for "R for Windows" (or similar) and launch it. This will (silently) load the language R. It will also open an inferior RStudio-like program called "RGui" -- you can close it.

3.**Launch RStudio** Search on AppsAnywhere for "RStudio" (or similar) and launch it.