project:
  type: book
  output-dir: docs

book:
  title: "MATH5835M Statistical Computing"
  author: "Matthew Aldridge"
  date: "30/09/25"
  chapters:
    - index.qmd
    - about.qmd
    - lectures/L01-intro.qmd
    - part: "Monte Carlo estimation"
      chapters:
        - lectures/L02-mc-intro.qmd
        - lectures/L03-mc-examples.qmd
        - lectures/L04-mc-error.qmd
        - lectures/L09-cv.qmd
        - lectures/L07-antithetic-1.qmd
        - problems/P1.qmd
        - lectures/L08-antithetic-2.qmd
        - lectures/L05-is-1.qmd
        - lectures/L06-is-2.qmd
    - part: "Random number generation"
      chapters:
        - lectures/L10-rng-intro.qmd
        - lectures/L11-lcg.qmd
        - problems/P2.qmd
        - lectures/L12-uniform-discrete.qmd
        - lectures/L13-inverse.qmd
        - lectures/L14-rejection.qmd
        - lectures/L15-envelope-1.qmd
        - lectures/L16-envelope-2.qmd
        - problems/P3.qmd
    - part: "MCMC"
      chapters:
        - lectures/L17-markov-intro.qmd
        - lectures/L18-markov-longrun.qmd
        - lectures/L19-markov-cont.qmd
        - lectures/L20-mh-1.qmd
        - lectures/L21-mh-2.qmd
        - lectures/L22-convergence.qmd
        - lectures/L23-bayes.qmd
        - problems/P4.qmd
    - part: "Bootstrap"
      chapters:
        - lectures/L24-empirical.qmd
        - lectures/L25-bootstrap.qmd
        - lectures/L26-bootstrap-error.qmd
        - lectures/L27-bootstrap-ci.qmd
        - problems/P5.qmd
    - lectures/L28-faq.qmd
    - coursework.qmd

format:
  html:
    theme: cosmo
    css: mystyle.css
  pdf:
    documentclass: scrreprt



