# Computational coursework {#coursework .unnumbered}

::: {.mysummary}
There is one piece of computational coursework for MATH5835M Statistical Computing. This coursework is worth 20% of the module mark.

The coursework sheet is available in **[here in HTML format](https://mpaldridge.github.io/math5835/coursework/math5835-coursework.html)** or **<a href="https://mpaldridge.github.io/math5835/coursework/math5835-coursework.Rmd">here in R Markdown format</a>**.

The deadline for the coursework will be the penultimate day of the Autumn term, **Thursday 11 December ** at **1400**. (There is also an optional deadline if you wish to get feedback on a draft of your work: Friday 5 December at 1400.)

Feedback on the final report and marks will be returned on Monday 12 January, the first day of the Spring term.
:::

## About the coursework

There is one piece of computational coursework for MATH5835M Statistical Computing. This coursework is worth 20% of the module mark.

This page contains all the administrative and organisational information about the coursework.

A coursework sheet contains the tasks you must carry out. The coursework sheet is available in **[here in HTML format](https://mpaldridge.github.io/math5835/coursework/math5835-coursework.html)** or **<a href="https://mpaldridge.github.io/math5835/coursework/math5835-coursework.Rmd">here in R Markdown format</a>**. The HTML page can be opened in a standard web browser. The R Markdown version (which I personally prefer) should be downloaded then opened in RStudio; I recommend using the "Visual" editor -- see the button in the top left of the editing window.

The are two deadlines for this work. 

1. There is the **main submission deadline** which is the penultimate day of term, **Thursday 11 December** at **1400**. You must submit your work by this time. Work that is submitted after this deadline will receive a penalty of 5% for every day or part-day late. Work that is more than 14 days late will not be marked and will receive 0. Work will be submitted electronically through Gradescope via the Minerva page for the module.

2. *Optionally*, you *may* also wish to get some brief informal feedback on your draft work before the main deadline. *If* you wish to get feedback on your draft work, you should submit that draft by Friday 6 December at 1400. I will return a small amount of general feedback about your work by Monday 9 December. I will not give a mark to your draft, and the feedback will be a brief sentence or too that may be of a little help when completing the final version of your work. The quality of your draft submission will have no effect (either positive or negative) on the mark for your main submission, and there is no penalty if you choose not to take advantage of this offer. You still must submit your final work by the main submission deadline, even if you submit a draft for feedback. No extensions can be offered on the deadline for this informal feedback.

The Gradescope submission for the final report will open after 1400 on Friday 6 December (to avoid drafts for optional feedback getting mixed up with final reports). The Gradescope submission for optional feedback on draft work will be open from the computer practical sessions in week 9.

You must comply with [the University's rules on academic integrity](https://students.leeds.ac.uk/info/10110/academic-integrity). [See below](#AI) for comments on use of AI.

If you encounter extraordinary unforeseeable personal circumstances that make it impossible for you to submit your coursework on time, you can apply for an deadline extension through [the usual mitigating circumstances procedure](https://students.leeds.ac.uk/info/10111/assessment/860/mitigating_circumstances). (Do not contact me about this -- I cannot unilaterally offer deadline extensions.)

## About your report

Your task is to write a short report in response to the tasks on the coursework sheet. Your report should include all the important R code you use and any important plots you draw. If I can't work out what R code you ran to get your results, I cannot award you marks for those results. Only include the code and figures relevant to your final and best solution -- I don't need or want to see earlier attempts or errors along the way, unless they genuinely help explain your final choices.

*All computational work must be done in R* -- no marks will be given for code written in Python or any other language. It is strongly recommended that you draw figures in R (with the possible exception of rough illustrative sketches, if you find them useful), but I do not insist on this.

You report must end with a declaration of AI use. [See below](#AI) for more on this.

I call your output a "report" because your work should be explained in detail, in full English-language sentences, with your solutions discussed and justified. The code and figures you include should be an integral part of your report, not just copy-pasted in at random, and should be fully explained within the text. However, other parts of a more formal "report", such as an introduction, literature review, conclusion, references, etc, are not required here.

There is *no page limit* for the report, although I expect that good reports will typically be around 5--8 pages. If your report is 4 pages or less, make sure you have completed all the tasks and fully explained your work. If your report has 10 pages or more, make sure you are not wandering from the point or including too many unnecessary figures.

Your report should be prepared electronically, but can be submitted in any sensible format -- I recommend PDF (whether produced by LaTeX, R Markdown, Microsoft Word, or any other way), but HTML or Word document are fine too.

## Computer practical and other help

There will be a computer practical in Week 9 where I will introduce the practical coursework in more detail. This is a good place to ask any questions you have about the coursework. You may wish to bring your own laptop to the computer practical, if you prefer working on that to on University computers.

Places where you can get help with the coursework include:

* In the computer practical session.

* In my office hours: Thursdays 1300--1400 in my office, 9.10n in the "Maths Research Deck" area on the 9th floor of the EC Stoner building at staircase 1. (It is unlikely I will have time to discuss computational work at the beginning or end of a lecture, although if your question is *extremely* short you can try.)

* By submitting your draft work for optional feedback, as discussed above.


## AI use

This coursework is rated AMBER for use of AI. This means that generative AI may be used in an "assistive role" only, provided you disclose (that is, tell me about) this use.

The following uses of generative AI go beyond merely "assistive" and are **not permitted**. Work that I suspect has used generative AI this way will be reported as an academic integrity case.

* Asking an LLM chatbot how to answer the questions on the problem sheet.

* Writing R code for you.

* Writing the text of your report for you.

The following uses of generative AI are only "assistive", and are permitted *provided you tell me that you used generative AI this way*. Work that uses AI this way, where the AI use *is* disclosed, will not be penalised in any way. Work that uses AI this way where the AI use is *not* disclosed will be treated as an academic integrity case.

* General revision of topics from the module, not particularly tailored to the coursework problems.

* Debugging almost-complete R code that you wrote yourself.

* Spell-checking and grammar-checking a report that you wrote yourself.

* Help with LaTeX code, if you choose to write your report in LaTeX.

All reports must end with a **declaration of generative AI use**.

* If you did not use generative AI at all, this can simply say: *"I did not use generative AI for the coursework project."*

* If you did use generative AI, this should say what system you used, what tasks it performed, and how you prompted it. Declarations like these should be one paragraph long, typically around 40--100 words.

For example, here are two hypothetical declarations:

> **Declaration of generative AI use (1).** The only place I used AI in this coursework was to spell- and grammar-check my report. I uploaded my Word document to Copilot, and prompted it: "Please check this report for spelling and grammar mistakes." It found 5 small errors, which I corrected.

> **Declaration of generative AI use (2).** I used AI to help when I had a bug in my R code that I couldn't fix myself. I copy-and-pasted my R script into ChatGPT, along with the text of the error from RStudio, and asked ChatGPT what the error was. It pointed out that, in drawing a graph, I had written `col = blue` without quotation-marks around `"blue"`. This was the only time I used AI for the coursework.



## R and RStudio on University computers

A quick reminder, if you need it, on how to access R and RStudio on University computers.

1. **Open the AppsAnywhere portal** This should be a link on the desktop. If invited to run any software, accept.

2. **Load the language R** Search on AppsAnywhere for "R for Windows" (or similar) and launch it. This will (silently) load the language R. It will also open an inferior RStudio-like program called "RGui" -- you can close it.

3.**Launch RStudio** Search on AppsAnywhere for "RStudio" (or similar) and launch it.

You can alternatively use the [Posit Cloud](https://posit.cloud) to access R and RStudio online.