# Problem Sheet 3 {#P3 .unnumbered}

<style>
.myanswers { 
display: none !important;
}
</style>


::: {.mysummary}
**[Full solutions](#P3-sols)** are now available.
:::





::: {.mysummary}
This is Problem Sheet 3, which covers material from Lectures 12 to 16. You should work through all the questions on this problem sheet in advance of the problems class, which takes place in the lecture of **Thursday 13 November**.

This problem sheet is to help you practice material from the module and to help you check your learning. It is *not* for formal assessment and does not count towards your module mark.

If you want some brief informal feedback on **Question 3 parts (a) and (b) and Question 6** (marked ★), you should submit your work electronically through Gradescope via the module's Minerva page by **1400 on Tuesday 11 November**. (If you hand-write solutions on paper, the easiest way to scan-and-submit that work is using the Gradescope app on your phone.) I will return some brief comments on your those two questions by the problems class on Thursday 13 November. Because this informal feedback, and not part of the official assessment, I cannot accept late work for any reason -- but I am always happy to discuss any of your work on any question in my office hours.

Full solutions will be released on Friday 14 November.
:::

::: {.content-visible when-format="html"}
{{< include P3-content.qmd >}}
:::