# Problem Sheet 5 {#P5 .unnumbered}

<style>
.myanswers { 
display: none !important;
}
</style>

<!--
::: {.mysummary}
**[Full solutions](#P2-sols)** are now available.
:::
-->


::: {.mysummary}
This is Problem Sheet 4, which covers material from Lectures 22 to 27. You should work through all the questions on this problem sheet in advance of the problems class, which takes place in the lecture of **Thursday 11 December**.

This problem sheet is to help you practice material from the module and to help you check your learning. It is *not* for formal assessment and does not count towards your module mark.

If you want some brief informal feedback on **Question 2** (marked ★), you should submit your work electronically through Gradescope via the module's Minerva page by **1400 on Tuesday 9 December**. (If you hand-write solutions on paper, the easiest way to scan-and-submit that work is using the Gradescope app on your phone.) I will return some brief comments on your those two questions by the problems class on Thursday 11 December. Because this informal feedback, and not part of the official assessment, I cannot accept late work for any reason -- but I am always happy to discuss any of your work on any question in my office hours.

Full solutions will be released on Friday 12 December.

Remember that **Thursday 11 December at 1400** is also the deadline for the module [coursework](#coursework)
:::

::: {.content-visible when-format="html"}
{{< include P5-content.qmd >}}
:::